# docker-compose development override for confidentialbackend service
version: "3.7"
services:
  confidentialbackend:
    command: sh -c "flask run --host 0.0.0.0 --port ${PORT:-8009}"
    environment:
      FLASK_ENV: development
    volumes:
    # set in .env
      - "${CONFIDENTIALBACKEND_CHECKOUT_DIR}/:/opt/app"
